- hosts: all
  become: yes
  tasks:
    # When writing your projects, make sure to use the roles included in maxhoesel.homelab
    # for applications like apache2 or nginx. These roles will install them for you and enable
    # homelab integrations like monitoring.
    - name: Hello World!
      debug:
        msg: Hello!

    # Backups are enabled by default. See inventory/group_vars/all/backup
    # for configuration options
    - name: Setup backups
      include_role:
        name: maxhoesel.homelab.setup_backup
