# Set this to a secret (vault-encrypted) backup password
backup_pubkey: "{{ lookup('hashi_vault', 'secret/data/projects/REPLACEME_PROJECT_NAME/backup:pubkey') }}"
backup_error_mail: "{{ project_email }}"
