# Set this to a secret (vault-encrypted) backup password
backup_passphrase: "{{ lookup('hashi_vault', 'secret/data/projects/REPLACEME_PROJECT_NAME/backup:borgmatic_passphrase') }}"
backup_error_mail: "{{ lookup('hashi_vault', 'secret/data/projects/REPLACEME_PROJECT_NAME/backup:borgmatic_email') }}"
