---
name: Build and Push Execution Environment
on:
  workflow_dispatch:
  push:
    paths:
      - execution-environment.yml
      - requirements.txt
      - collections/requirements.yml
      - tox.ini
      - '.github/**'
  schedule:
    - cron: "4 0 * * 5"

jobs:
  image_name:
    name: Get Image Name
    runs-on: ubuntu-22.04
    outputs:
      image_name: "${{ steps.image_name.outputs.image_name }}"
    steps:
      - id: image_name
        run: |
          export IMGNAME=$(python3 -c 'print("".join("${{ github.repository }}".split("/")[1]))')
          echo "::set-output name=image_name::$IMGNAME"
  build:
    name: Build and Push EE
    needs: image_name
    uses: maxhoesel-homelab/workflows/.github/workflows/build-ct-tox.yml@main
    with:
      image_name: ${{ needs.image_name.outputs.image_name }}
    secrets:
      registry_username: "${{ secrets.QUAY_USERNAME }}"
      registry_password: "${{ secrets.QUAY_TOKEN }}"
